"""
Student information for this assignment:

On my/our honor, Xinyue Yu, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID: xy4677
"""

def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest = 0
    n = len(s)
    for i in range(n):
        for j in range(i, n):
            substring = s[i:j+1]
            freq = [0] * 256
            valid = True
            for char in substring:
                freq[ord(char)] += 1
                if freq[ord(char)] > 1:
                    valid = False
            if valid:
                longest = max(longest, len(substring))
    return longest


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    longest = 0
    n = len(s)
    for i in range(n):
        freq = [0] * 256
        valid = True
        for j in range(i, n):
            char_index = ord(s[j])
            freq[char_index] += 1
            if freq[char_index] > 1:
                valid = False
            if valid:
                longest = max(longest, j - i + 1)
    return longest


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    n = len(s)
    longest = 0
    freq = [0] * 256
    left = 0
    for right in range(n):
        char_index = ord(s[right])
        freq[char_index] += 1
        while freq[char_index] > 1:
            freq[ord(s[left])] -= 1
            left += 1
        longest = max(longest, right - left + 1)
    return longest
